FROM golang:1.25-alpine AS builder
WORKDIR /app

# Copia Arquivos de dependências
COPY go.mod go.sum ./
RUN go mod download

# Copia o código fonte
COPY . .

# Compila o binário de forma estática
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

## Estágio 2: Imagem final
FROM gcr.io/distroless/static-debian12

WORKDIR /app

#Só roda o binário compilado e mais nada, sem dependências de sistema.
COPY --from=builder /app/server .
EXPOSE 8080
CMD ["./server"]
